### PR TITLE
Drag and drop fix on Qt6 and minimal testing of the feature

### PR DESCRIPTION
**Pull request by MatthieuDartiailh**
QTest is quite bugged when it comes to mouse movement (cannot keep a button down) and in addition QDrag.exec is blocking (at least on Windows) which makes testing this feature a bit challenging. Using PyAutoGUI I managed to get a basic test working but it does not exercise dragLeave (it is emitted when I test manually but not in the automatic test and I have no real idea why).

### CODE REVIEW

**Comment by MatthieuDartiailh** [comment]
@bburan Could you enable GH actions to see if the tests work in CIs ?

**Comment by bburan** [comment]
That's annoying about QTest. Trying to figure out this CI thing. It seems like it is enabled (I created a dummy branch and added one of the GH actions templates and got a message notifying me it attempted to run). When I click on the actions tab, I don't see any available actions to run. I'm wondering if this is a related issue? 

https://github.community/t/github-action-workflow-is-executed-for-a-pr-from-a-forked-repo-if-the-pr-changes-the-workflow-file/16059

**Comment by bburan** [comment]
@MatthieuDartiailh I'm wondering if the CI did not trigger because the default branch for this repo was still set to an old version of Enaml's master branch (which did not have CI configured). I updated the base branch to main and pulled in all the changes from nucleic/enaml. I now see CI running for the main branch so that at least is working. I think, now, to trigger a CI we need to push a new commit to this branch (then I will need to approve it since you're a first-time contributor and you've made changes to the CI config file). Since I don't have commit privileges for MatthieuDartiailh/enaml, I need you to try pushing a new commit to that branch then we'll see if the actions trigger.

**Comment by MatthieuDartiailh** [comment]
I pushed a commit but I do not see anything.  I guess it is because CI are enabled only for PRs against main my bad... I wanted to be able to build everything we need into your PR, but it may make more sense to have a tracking issue and several small PRs addressing each one issue.

**Comment by MatthieuDartiailh** [comment]
Closing in favor of https://github.com/nucleic/enaml/pull/491

**Pull request closed without merging**
